/*
 * Rates API
 *
 * This is a store server.
 *
 * API version: 1.0.0
 * Contact: njangam169@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Rental struct {

	StartDate string `json:"startDate"`

	EndDate string `json:"endDate"`

	CarType string `json:"carType"`
}
